### ISSUE TITLE
Declares sinon as a dependency, and sometimes monkey-patches its own copy

### ISSUE THREAD

**Issue by rprieto** [L7labs/sinon-bluebird#3]
It seems sinon is declared as a `dependency`. Since we use `sinon < 1.12`, sinon-bluebird was getting its own copy in `sinon-bluebird/node_modules`, and attaching the new keywords there.

```
{
  "dependencies": {
    "bluebird": "^2.9.12",
    "sinon": "^1.12.2"
  },
  "peerDependencies": {
    "sinon": "1.x"
  }
}
```

It's also declared as a `peerDependency`, which sounds good, so maybe `dependencies` is an accident? Since it's used in the tests, should it be a `devDependency` instead?

**Comment by toddbluhm** [comment]
Good catch! 

Actually I am going to make both `bluebird` and `sinon` devDependencies and add `bluebird` in peerDependencies. My thought is, well no need for our package to install bluebird too, because its very likely anyone using this package will already have both `bluebird` and `sinon` installed. I will make a note of it in the README too. Does that work for your needs?

**Comment by rprieto** [comment]
That sounds great to me :+1:  Thanks for the quick reply!

_Note:_ probably worth following the `npm` conversations about peerDependencies, looks like there will be changes at some point but for now that makes sense to me.

**Comment by toddbluhm** [comment]
Yeah, I have been following those peerDependencies conversations and last I check they had not made up their mind on removing it. I will keep a close eye on it of course and update this package as necessary. I will publish the new npm shortly...should be v1.0.2

**Comment by rprieto** [comment]
Sounds good, thanks again :)

**Comment by toddbluhm** [comment]
Its published! And thanks for helping out :)
