### ISSUE TITLE
.stub().rejects() and .stub().returns(Promise.reject(...)) returning different values

### ISSUE THREAD

**Issue by mayorbyrne** [L7labs/sinon-bluebird#8]
`.rejects()` and `.returns(Promise.reject())` are returning two different values.  I would expect them to return the same, since `.resolves()` and `.returns(Promise.resolve())` do so.

``` js
var sinon = require('sinon-bluebird'),
  BPromise = require('bluebird'),
  x;

x = sinon.stub().rejects('goodbye');
x().catch(function(err){
  console.log(err, typeof err); // [Error: goodbye] 'object'
});

x = sinon.stub().returns(BPromise.reject('goodbye'));
x().catch(function(err){
  console.log(err, typeof err); // goodbye string
});
```

**Comment by toddbluhm** [comment]
Yes that is correct behavior as noted by the README.md:

> **.rejects(value)**
> 
> Returns a rejected bluebird promise with the given value.
> 
> _Note: If the given value is a String, that string will be wrapped in an Error object and will be on the >message property._

I must admit this is a bit of a sore spot for me though, originally I liked the convenience, but looking at it now through a bit more experience I realize I should have probably left that up to the end-user rather than forcing it into a string.

Unfortunately, if I am to change the behavior to no longer auto wrap a string into an `Error` object, that would be a major breaking change and we would need to bump the lib up to `2.0.0`. Not sure if I am ready to do that yet.

I will think about this for a little while and get back to you about my decision soon.

**Comment by toddbluhm** [comment]
Okay so I am getting back you and I agree. We should change it, so that passing a `String` into `.rejects` leaves it unmodified (so no `Error` wrapping). Like I said earlier, this will cause a major version bump, but I am okay with that. I will get started on this as soon as I have time.
